// ============================================================================
//  strategy_types.h  -  data model for the strategy (RTS) test state
//
//  Everything lives in fixed-size arrays inside one StrategyWorld singleton
//  (no malloc). A slot is "alive" when its .active flag is set; freeing is
//  just clearing the flag. Positions are Vector3 on the y = 0 ground plane.
//
//  Per-kind numbers (HP, damage, ranges, costs, ...) live in the def tables
//  in strategy_defs.c - NOT here. Stats are resolved ONCE at spawn:
//      base UnitDef  x  faction difficulty mods  x  training-building buffs
//  and stored on the Unit instance, so combat/gather code never looks up
//  tables and difficulty never touches already-living units.
// ============================================================================

#ifndef STRATEGY_TYPES_H
#define STRATEGY_TYPES_H

#include "raylib.h"
#include <stdbool.h>

// -- Capacities --------------------------------------------------------------
#define STRAT_MAX_UNITS      96
#define STRAT_MAX_BUILDINGS  24
#define STRAT_MAX_NODES      48
#define STRAT_FACTIONS       2      // 0 = player (blue), 1 = enemy (red)
#define FACTION_NEUTRAL      2      // animals: no stockpile, no color entry -
                                    //   always guard before indexing by faction

// -- Tuning (world-level; per-kind numbers live in strategy_defs.c) ----------
#define STRAT_GROUND_HALF    25.0f  // ground spans [-HALF, +HALF] on x and z
#define STRAT_UNIT_RADIUS    0.35f
#define STRAT_CARRY_MAX      5      // resource units carried before returning
#define STRAT_AI_PERIOD      1.0f   // seconds between enemy "think" ticks (Hard)
#define STRAT_RETARGET_RADIUS 10.0f // depleted node: search for the next one here
#define STRAT_ANIMAL_COUNT   6      // weak neutral critters spawned at init
#define STRAT_ANIMAL_STRONG_COUNT 3 // strong neutral beasts spawned at init
#define STRAT_AI_ATTACK_SQUAD 4     // idle enemy soldiers needed for an attack wave

// Neutral animal reactions to being hit.
#define STRAT_FLEE_PACK_RADIUS 5.0f // weak animals this close flee together
#define STRAT_FLEE_DIST        7.0f // how far away from the attacker they run

// Templar blessing / healing.
#define STRAT_BLESS_PERIOD   5.0f   // seconds between blessings near a target
#define STRAT_BLESS_TIME     0.6f   // pause while the sparkles play
#define STRAT_HEAL_AMOUNT    8.0f   // hp restored by one healer blessing
#define STRAT_HEAL_COST      1     // providence consumed by one healing

// Construction / repair (worker-driven).
#define STRAT_BUILD_RANGE    1.8f   // worker must be this close to build/repair
#define STRAT_REPAIR_RATE    12.0f  // building hp restored per second per worker

// Node-tending buildings (farm -> wheat, forestry -> wood): an assigned worker
// walks to a free spot nearby and plants a node. Once TEND_MAX nodes stand
// near the building the worker instead harvests the nearest one to depletion,
// then resumes planting. Amounts come from the building def (tendAmount).
#define STRAT_TEND_RANGE   6.0f   // how far from the building a worker plants
#define STRAT_TEND_SPACING 1.4f   // min gap to any node/building at a plant spot
#define STRAT_TEND_PERIOD  1.5f   // seconds to plant one node once in position
#define STRAT_TEND_MAX     8       // planted nodes near the building before gathering

// Quarry: spend providence to conjure a fresh stone node beside it.
#define STRAT_QUARRY_STONE_PROV   2     // providence spent per spawn
#define STRAT_QUARRY_STONE_AMOUNT 100   // stone in the spawned node
#define STRAT_QUARRY_STONE_SPREAD 3.0f  // jitter radius around the quarry

typedef enum {
    RES_WOOD = 0,
    RES_STONE,
    RES_FOOD,
    RES_PROVIDENCE,     // global currency generated by templar blessings;
                        //   never carried or dropped off (no node yields it)
    RES_COUNT
} ResourceKind;

typedef enum {
    NODE_TREE = 0,      // yields RES_WOOD
    NODE_ROCK,          // yields RES_STONE
    NODE_WHEAT,         // yields RES_FOOD
    NODE_CORPSE,        // yields RES_FOOD (left behind by hunted animals)
} NodeKind;

typedef enum {
    BLD_HOUSE = 0,      // raises the pop cap, accepts nothing
    BLD_LOGGING,        // wood dropoff
    BLD_QUARRY,         // stone dropoff
    BLD_BARRACKS,       // trains melee + ranged soldiers
    BLD_FARM,           // workers assigned to it generate food; food dropoff
    BLD_TOWN_HALL,      // CRITICAL initial building: trains workers, accepts
                        //   wood + stone + food
    BLD_CHANTRY,        // trains templars (providence economy)
    BLD_FORESTRY,       // auto-plants fresh tree nodes nearby over time
    BLD_COUNT
} BuildingKind;

typedef enum {
    KIND_WORKER = 0,        // gathers/farms/hunts, weak in a fight
    KIND_SOLDIER,           // melee fighter, cannot gather
    KIND_RANGED,            // bow soldier: kites at near-max shooting distance
    KIND_TEMPLAR,           // non-combat: follows own units, blesses gatherers,
                            //   each blessing generates RES_PROVIDENCE
    KIND_TEMPLAR_HEALER,    // follows wounded own units, blessing heals them
                            //   and CONSUMES providence
    KIND_ANIMAL_WEAK,       // neutral critter: when one is hit the pack flees
    KIND_ANIMAL_STRONG,     // neutral beast: when hit the pack fights back
    UNIT_KIND_COUNT
} UnitKind;

typedef enum {
    UNIT_IDLE = 0,
    UNIT_MOVE,          // walking to .target
    UNIT_GATHER,        // walking to / working .targetNode
    UNIT_RETURN,        // carrying resources to the nearest ACCEPTING building
    UNIT_ATTACK,        // chasing / hitting .targetUnit OR .targetBuilding
    UNIT_FARM,          // working .targetBuilding (a farm), food straight to stockpile
    UNIT_FLEE,          // animal running away from an attacker (to .target)
    UNIT_FOLLOW,        // templar shadowing .targetUnit
    UNIT_BLESS,         // templar performing the sparkly blessing on .targetUnit
    UNIT_BUILD,         // worker raising a scaffold (.targetBuilding) to full
    UNIT_REPAIR,        // worker restoring a damaged building (.targetBuilding)
} UnitState;

typedef struct {
    bool         active;
    int          faction;
    UnitKind     kind;
    Vector3      pos;
    Vector3      target;            // move destination (UNIT_MOVE / UNIT_FLEE)
    UnitState    state;
    float        hp, maxHp;

    // Stats resolved at spawn (def x difficulty x building buffs); see header.
    float        damage;
    float        attackRange;
    float        attackPeriod;      // seconds between hits
    float        preferredRange;    // >0: ranged unit's kiting stand-off distance
    float        moveSpeed;
    float        sightRange;        // auto-aggro scan radius
    float        gatherTime;        // seconds per chop/mine tick
    float        farmPeriod;        // seconds per food unit while farming

    float        attackCooldown;    // seconds until the next hit is allowed
    int          targetUnit;        // units[] index: UNIT_ATTACK victim, or the
                                    //   templar's FOLLOW/BLESS target (-1 = none)
    int          targetNode;        // nodes[] index while UNIT_GATHER (-1 = none)
    int          targetBuilding;    // buildings[] index while attacking one or
                                    //   farming (-1 = none); never set with targetUnit
    int          carryAmount;       // 0..STRAT_CARRY_MAX
    ResourceKind carryKind;
    float        gatherTimer;       // accumulates toward gatherTime / farmPeriod,
                                    //   and paces the templar bless cycle
    bool         selected;          // player faction only
    int          controlGroup;      // 0 = none, 1..3 = ctrl+digit group
} Unit;

typedef struct {
    bool         active;
    BuildingKind kind;
    int          faction;
    Vector3      pos;
    float        hp, maxHp;
    int          trainKind;         // UnitKind in production, -1 = idle
    float        trainProgress;     // seconds spent on the current trainee
    float        trainCooldown;     // anti-spam: seconds until training may restart

    // Production queue: kinds waiting behind the current trainee (paid for on
    // enqueue). The active trainee is trainKind; these are the ones after it.
#define BLD_MAX_QUEUE 8
    UnitKind     trainQueue[BLD_MAX_QUEUE];
    int          trainQueueCount;   // 0..BLD_MAX_QUEUE

    // Construction: a freshly placed building starts as a scaffold that a
    // worker must build up before it functions (no train / dropoff / popcap).
    bool         underConstruction;
    float        buildProgress;     // seconds accrued by workers, toward buildTime

    // Rally: trained units walk here on completion instead of going idle.
    Vector3      rally;
    bool         hasRally;

    // Timed buffs (reserved: filled by future upgrades / templar blessings
    // on buildings; property indices to be defined with the upgrade system).
#define BLD_MAX_ACTIVE_BUFFS 4
    struct { int property; float mul; float remaining; } buffs[BLD_MAX_ACTIVE_BUFFS];
} Building;

typedef struct {
    bool     active;
    NodeKind kind;
    Vector3  pos;
    int      remaining;             // resource units left; 0 -> despawn
} ResourceNode;

// Per-faction difficulty multipliers, resolved once at init from the
// settings difficulty. The player's row is always identity; FACTION_NEUTRAL
// gets an identity row too so UnitSpawn can index by faction unguarded.
typedef struct {
    float hpMul, dmgMul;        // unit maxHP / attack damage
    float gatherMul;            // gather + farm time (bigger = slower)
    float sightMul;             // auto-aggro scan radius
    float aiPeriodMul;          // stretches the faction brain tick
    float refundBonus;          // added to building sell refund rate
} FactionMods;

typedef struct {
    Unit         units[STRAT_MAX_UNITS];
    Building     buildings[STRAT_MAX_BUILDINGS];
    ResourceNode nodes[STRAT_MAX_NODES];
    int          stockpile[STRAT_FACTIONS][RES_COUNT];

    FactionMods  mods[STRAT_FACTIONS + 1];  // [FACTION_NEUTRAL] = identity
    float        aiPeriod;                  // STRAT_AI_PERIOD * enemy aiPeriodMul

    // Camera: fixed-pitch RTS view. The camera is DERIVED every frame from
    // focus + zoom, so panning/zooming only touch these two fields.
    Camera3D camera;
    Vector2  camFocus;              // ground point the camera looks at (x, z)
    float    camZoom;               // scales the fixed offset (clamped)

    // Input / UI state
    bool      pressInWorld;         // LMB press began in the world (not on GUI);
                                    //   drag/release selection only acts on these
    bool      dragging;             // LMB held and moved past the drag threshold
    Vector2   dragStart;            // game-canvas pixels (Screen2Target space)
    int       placing;              // BuildingKind ghost being placed, -1 = none
    int       selectedBuilding;     // buildings[] index (player), -1 = none;
                                    //   mutually exclusive with unit selection
    bool      buildMenuOpen;        // command panel currently shows the build list
    int       gameOver;             // -1 = playing, else the WINNING faction index
    float     aiTimer;              // countdown to the next enemy think tick
    Rectangle guiBlock;             // REAL-screen px area where the GUI owns the
                                    //   mouse (command panel); world clicks ignore it
} StrategyWorld;

#endif // STRATEGY_TYPES_H
